
--Exclude ACQ paygroup for SafeBuilt
sELECT * FROM U_EANTFMLSAF_drvTbl WHERE drveeid IN (SELECT EECEEID FROM EMPCOMP WHERE EECPAYGROUP = 'ACQ')
sELECT * FROM U_EANTFMLSAF_drvTbl_LOB WHERE drveeid IN (SELECT EECEEID FROM EMPCOMP WHERE EECPAYGROUP = 'ACQ')
 sELECT * FROM U_EANTFMLSAF_drvTbl_LOB WHERE drveeid IN (SELECT EECEEID FROM EMPCOMP WHERE EECPAYGROUP = 'ACQ')


 