SELECT bdmEEID as BdmEEID,
bdmCOID AS bdmCOID, 
'Y' AS bdmEECode,
SUM (bdmEEAmt) AS bdmEEAmt
from dbo.U_dsi_BDM_ECLOHSACON WITH (NOLOCK)
WHERE bdmDedcode IN ('HSADE', 'HSAEE', 'HSDCU', 'HSECU')
GROUP BY bdmEEID, bdmCOID AS BdmFlattenedEE

SELECT bdmEEID as BdmEEID,
bdmCOID AS bdmCOID, 
'Y' AS bdmEECode,
SUM (bdmERAmt) AS bdmERAmt
from dbo.U_dsi_BDM_ECLOHSACON WITH (NOLOCK)
WHERE bdmDedcode IN ('HSADE', 'HSAEE', 'HSDCU', 'HSECU')
GROUP BY bdmEEID, bdmCOID AS BdmFlattenedER

SELECT *
from dbo.U_ECLOHSACON_PDedHist

SELECT pdhEEID,
PdhEEHSADE + PdhEEHSAEE  + PdhEEHSDCU + PdhEEHSDCU AS pdhEmpAmt
FROM dbo.U_ECLOHSACON_PDedHist



PdhERHSADE + PdhERHSAEE + PdhERHSDCU + PdhERHSEC

SELECT pdhEEID,
PdhERHSADE + PdhERHSAEE + PdhERHSDCU + PdhERHSECU  AS pdhEmpAmt
FROM dbo.U_ECLOHSACON_PDedHist


SELECT *
FROM dbo.U_ECLOHSACON_drvTbl

SELECT pdhEEID,
		  CAST(PdhEEHSADE + PdhEEHSAEE + PdhEEHSDCU + PdhEEHSDCU AS VARCHAR(10)) AS pdhEEAmt

select *
FROM dbo.U_ECLOHSACON_PDedHist


SELECT SUBSTRING('10.0000',1, LEN('10.0000')-2)

SELECT *
FROM dbo.U_ECLOHSACON_PDedHist

