--sp_getEEID 'Gibbs' -- DOA55Y000020
--sp_GetEEID 'Morgan' -- C39X3Z04C0K0
--sp_getEEID 'Fraley' -- CMK14S000020
--sp_getEEID 'Groves' -- CK1IQQ001020
--sp_getEEID 'Donovan' -- COCT3S000020
--sp_getEEID 'Walker' -- C39X4004Q0K0
--sp_getEEID 'Wright' -- C39X3K00E0K0
--sp_getEEID 'Thompson' -- C39X8E02Y0K0

--DECLARE @EEID VARCHAR(12) = 'DOA55Y000020';
--DECLARE @EEID VARCHAR(12) = 'C39X3Z04C0K0';
--DECLARE @EEID VARCHAR(12) = 'CMK14S000020';
--DECLARE @EEID VARCHAR(12) = 'CK1IQQ001020';
--DECLARE @EEID VARCHAR(12) = 'COCT3S000020';
--DECLARE @EEID VARCHAR(12) = 'C39X4004Q0K0';
--DECLARE @EEID VARCHAR(12) = 'C39X3K00E0K0';
DECLARE @EEID VARCHAR(12) = 'C39X8E02Y0K0';


select * from dbo.U_EGRDHW834E_DrvTbl_2300
where drvEEID = @EEID

/*
SELECT BdmEEID AS CI_BdmEEID, BdmCOID AS CI_BdmCOID,
				CASE WHEN BdmCI IS NOT NULL AND BdmCIS IS NOT NULL THEN BdmCI 
				WHEN BdmCI IS NOT NULL AND BdmCIEE IS NOT NULL THEN BdmCI 
				WHEN BdmCIEE IS NOT NULL AND BdmCIS IS NOT NULL THEN BdmCIS
				ELSE RTRIM(LTRIM(ISNULL(BdmCI,'') + ISNULL(BdmCIS, '') + ISNULL(BdmCIEE, '')))
				END AS BdmCodeToUse
				,CASE WHEN BdmCI IS NOT NULL AND BdmCIS IS NOT NULL THEN BdmCIBO 
				WHEN BdmCI IS NOT NULL AND BdmCIEE IS NOT NULL THEN BdmCIBO 
				WHEN BdmCIEE IS NOT NULL AND BdmCIS IS NOT NULL THEN BdmCISBO
				ELSE RTRIM(LTRIM(ISNULL(BdmCIBO,'') + ISNULL(BdmCISBO, '') + ISNULL(BdmCIEEBO, '')))
				END AS BdmBenOptionToUse
			FROM (
					SELECT BdmEEID, BdmCOID
						,MAX(CASE WHEN BdmDedCode = 'CI' THEN BdmDedCode END) AS BdmCI
						,MAX(CASE WHEN BdmDedCode = 'CIS' THEN BdmDedCode END) AS BdmCIS
						,MAX(CASE WHEN BdmDedCode = 'CIEE' THEN BdmDedCode END) AS BdmCIEE
						,MAX(CASE WHEN BdmDedCode = 'CI' THEN BdmBenOption END) AS BdmCIBo
						,MAX(CASE WHEN BdmDedCode = 'CIS' THEN BdmBenOption END) AS BdmCISBo
						,MAX(CASE WHEN BdmDedCode = 'CIEE' THEN BdmBenOption END) AS BdmCIEEBo
					FROM dbo.U_dsi_bdm_EGRDHW834E WITH (NOLOCK)
					WHERE BdmDedCode IN ('CI','CIS','CIEE')
					AND BdmRecType = 'EMP'
					GROUP BY BdmEEID, BdmCOID) AS BIB
					where BdmEEID = 'DOA55Y000020';



SELECT *
FROM dbo.U_dsi_bdm_EGRDHW834E WITH (NOLOCK)
WHERE BdmDedCode IN ('CI','CIS','CIEE')
and BdmEEID = 'DOA55Y000020';

*/