--sp_getEEID 'Tolliver' -- C39XAS02Z0K0
--sp_GetEEID 'Andrews' -- E2RB47000020
--sp_getEEID 'Morgan' -- C39X3Z04C0K0

--DECLARE @EEID VARCHAR(12) = 'C39XAS02Z0K0';
--DECLARE @EEID VARCHAR(12) = 'E2RB47000020';
DECLARE @EEID VARCHAR(12) = 'C39X3Z04C0K0';

select * from dbo.U_EGRDHW834E_DrvTbl_2300
where drvEEID = @EEID
AND drvHD03_InsuranceLineCode = 'AG'
AND drvHD05_CoverageLevelCode = 'EMP'

select * from dbo.U_dsi_bdm_EGRDHW834E WITH (NOLOCK)
where BdmEEID = @EEID
and BdmDedCode IN ('CI','CIS','CIEE')
and BdmRecType = 'EMP'



SELECT BdmEEID, BdmCOID,
	CASE WHEN BdmCI IS NOT NULL AND BdmCIS IS NOT NULL THEN BdmCI 
	WHEN BdmCI IS NOT NULL AND BdmCIEE IS NOT NULL THEN BdmCI 
	WHEN BdmCIEE IS NOT NULL AND BdmCIS IS NOT NULL THEN BdmCIS
	ELSE RTRIM(LTRIM(ISNULL(BdmCI,'') + ISNULL(BdmCIS, '') + ISNULL(BdmCIEE, '')))
	END AS BdmCodeToUse
	,CASE WHEN BdmCI IS NOT NULL AND BdmCIS IS NOT NULL THEN BdmCIBO 
	WHEN BdmCI IS NOT NULL AND BdmCIEE IS NOT NULL THEN BdmCIBO 
	WHEN BdmCIEE IS NOT NULL AND BdmCIS IS NOT NULL THEN BdmCISBO
	ELSE RTRIM(LTRIM(ISNULL(BdmCIBO,'') + ISNULL(BdmCISBO, '') + ISNULL(BdmCIEEBO, '')))
	END AS BdmBenOptionToUse
FROM (
		SELECT BdmEEID, BdmCOID
			,MAX(CASE WHEN BdmDedCode = 'CI' THEN BdmDedCode END) AS BdmCI
			,MAX(CASE WHEN BdmDedCode = 'CIS' THEN BdmDedCode END) AS BdmCIS
			,MAX(CASE WHEN BdmDedCode = 'CIEE' THEN BdmDedCode END) AS BdmCIEE
			,MAX(CASE WHEN BdmDedCode = 'CI' THEN BdmBenOption END) AS BdmCIBo
			,MAX(CASE WHEN BdmDedCode = 'CIS' THEN BdmBenOption END) AS BdmCISBo
			,MAX(CASE WHEN BdmDedCode = 'CIEE' THEN BdmBenOption END) AS BdmCIEEBo
		FROM dbo.U_dsi_bdm_EGRDHW834E WITH (NOLOCK)
		WHERE BdmDedCode IN ('CI','CIS','CIEE')
		AND BdmRecType = 'EMP'
		GROUP BY BdmEEID, BdmCOID) AS BIBdm
WHERE BdmEEID = @EEID

