

SELECT EepNameLast, EepNameFirst, EepSSN
FROM dbo.U_dsi_bdm_ESUNLNC834 WITH (NOLOCK)
JOIN dbo.EmpPers WITH (NOLOCK)
	ON EepEEID = BdmEEID 
WHERE BdmDedCode IN ('CANP1','CANP2')
AND BdmBenOption IN ('EEF','EEDPF')
AND BdmEEID NOT IN ('D0CSSJ02J040','D0CTYL048040','D0CTYN034040','D0CTYU03I040')
ORDER BY BdmEEID, CASE WHEN BdmRecType = 'Emp' THEN 1 ELSE 2 END

/*
SELECT DISTINCT BdmEEID 
FROM dbo.U_dsi_bdm_ESUNLNC834 WITH (NOLOCK)
WHERE BdmDedCode IN ('CANP1','CANP2')
AND BdmBenOption IN ('EEF','EEDPF')
AND BdmRecType = 'DEP'*/

