--sp_getEEID 'Boudreaux' -- 9LTB7Z0000K0
--sp_getEEID 'Dempsey' -- A2GVLG0010K0

DECLARE @EEID VARCHAR(12) = '9LTB7Z0000K0'
--DECLARE @EEID VARCHAR(12) = 'A2GVLG0010K0'

select * from dbo.U_dsi_BDM_EDISCCOBRA WITH (NOLOCK) where BdmEEID = @EEID

select * from dbo.U_EDISCCOBRA_drvTbl_QBPLANINITIAL WHERE drvEEID = @EEID

select * from dbo.U_EDISCCOBRA_drvTbl_QBPLANMEMBERSPECIFICRATEINITIAL where drvEEID = @EEID