--sp_getEEID 'Hartenstein' -- 9AQTZG0000K0   or    9CCWR90000K0

--DECLARE @EEID VARCHAR(9) = '9CCWR90000K0'; -- Dunn?
--DECLARE @EEID VARCHAR(9) = '9AQTZG0000K0'; -- Dunn
--DECLARE @EEID VARCHAR(9) = '9CCVKH00E0K0'; -- Bowman
--DECLARE @EEID VARCHAR(9) = '9CCVKN0000K0'; -- Hartenstein

SELECT * FROM dbo.U_EWESHSAEXP_drvTbl_CT
 WHERE drvEEID = @EEID



 SELECT * FROM dbo.U_EWESHSAEXP_drvTbl_PT
 WHERE drvEEID = @EEID


 SELECT * FROM dbo.U_EWESHSAEXP_drvTbl_EN
 WHERE drvEEID = @EEID


